const categories = [
  ["business-cards", "Business Cards", "Premium cards that make every introduction count.", "BC"],
  ["marketing", "Marketing Materials", "Campaign-ready flyers, brochures and posters.", "MP"],
  ["corporate-gifting", "Corporate Gifting", "Thoughtful branded gifts for teams, clients and milestones.", "CG"],
  ["expo-materials", "Expo Materials", "Professional displays and print essentials for events and exhibitions.", "EM"],
  ["packaging", "Labels & Packaging", "Thoughtful packaging for products, parcels and retail.", "LP"],
  ["signage", "Signage & Displays", "High-impact signage for stores, events and workspaces.", "SD"],
  ["apparel", "Custom Apparel", "Quality branded clothing for teams, events and retail.", "CA"],
  ["gifts", "Personalised Gifts", "Photo-led gifts, keepsakes and display pieces.", "PG"],
  ["stationery", "Office Stationery", "Branded essentials for professional everyday use.", "OS"],
  ["same-day", "Same-Day Prints", "Select print essentials produced in as little as four hours.", "4H"],
  ["bulk", "Bulk Printing", "Reliable volume printing for campaigns, teams and rollouts.", "BP"]
];

// Canonical PrintOasis catalog. Prices are INR for the listed minimum quantity.
const products = [
  ["classic-business-cards", "Square Business Cards", "business-cards", 499, 100, 4.8, "Popular", "Distinctive square cards on premium 350 GSM stock with precise, rich colour.", "2.5 x 2.5 in|3 x 3 in", "Matte|Uncoated", "Single-sided|Double-sided", "cobalt"],
  ["premium-foil-cards", "Raised Foil Business Cards", "business-cards", 999, 100, 4.9, "Recommended", "Luxurious thick cards with tactile raised gold or silver foil details.", "3.5 x 2 in", "Soft-touch|Textured", "Gold foil|Silver foil", "ink"],
  ["spot-uv-business-cards", "Spot UV Business Cards", "business-cards", 849, 100, 4.8, "", "Matte laminated cards with a high-gloss Spot UV accent for selective detail.", "3.5 x 2 in", "350 GSM matte laminated", "Single-sided|Double-sided", "ink"],
  ["standard-business-cards", "Standard Business Cards", "business-cards", 399, 100, 4.6, "", "Dependable full-colour cards for everyday networking, meetings and handouts.", "3.5 x 2 in", "300 GSM matte|300 GSM gloss", "Single-sided|Double-sided", "cobalt"],
  ["premium-business-cards", "Premium Business Cards", "business-cards", 699, 100, 4.8, "Recommended", "Thick, refined business cards made for a confident first impression.", "3.5 x 2 in", "400 GSM premium stock", "Single-sided|Double-sided", "ink"],
  ["matte-business-cards", "Matte Business Cards", "business-cards", 549, 100, 4.7, "", "Smooth matte cards with a low-glare finish and crisp writing surface.", "3.5 x 2 in", "350 GSM matte laminated", "Single-sided|Double-sided", "cobalt"],
  ["gloss-business-cards", "Gloss Business Cards", "business-cards", 549, 100, 4.6, "", "High-shine business cards that make colour, photography and logos stand out.", "3.5 x 2 in", "350 GSM gloss laminated", "Single-sided|Double-sided", "yellow"],
  ["textured-business-cards", "Textured Business Cards", "business-cards", 899, 100, 4.7, "New", "Tactile textured stock for distinctive personal and premium brand cards.", "3.5 x 2 in", "Linen texture|Hammered texture", "Single-sided|Double-sided", "coral"],
  ["transparent-business-cards", "Transparent Business Cards", "business-cards", 1199, 100, 4.7, "New", "Clear frosted cards for modern brands, salons, studios and creative teams.", "3.5 x 2 in", "Frosted PVC|Clear PVC", "White ink|Full colour", "mint"],
  ["eco-friendly-business-cards", "Eco-Friendly Business Cards", "business-cards", 649, 100, 4.7, "", "Recycled-stock business cards with a natural, considered finish.", "3.5 x 2 in", "Recycled kraft|Recycled white", "Single-sided|Double-sided", "mint"],

  ["folded-brochures", "Premium Folded Brochures", "marketing", 749, 50, 4.7, "Popular", "Crisp, professionally folded brochures for menus, launches and sales kits.", "A4 tri-fold|A4 bi-fold|A3 bi-fold", "130 GSM gloss|170 GSM matte", "Single-sided|Double-sided", "coral"],
  ["event-posters", "Presentation Folders", "marketing", 1199, 25, 4.7, "", "Professional folders with business-card slots for proposals, sales kits and meetings.", "A4", "300 GSM matte|350 GSM laminated", "Single-sided|Double-sided", "yellow"],
  ["professional-flyers", "Professional Flyers", "marketing", 449, 50, 4.7, "Recommended", "Marketing flyers with vivid colour reproduction for promotions, menus and handouts.", "A5|A4|DL", "130 GSM gloss|170 GSM matte", "Single-sided|Double-sided", "coral"],
  ["marketing-booklets", "Marketing Booklets", "marketing", 1299, 25, 4.7, "", "Multi-page booklets for product stories, reports, programmes and guides.", "A5|A4", "130 GSM gloss|170 GSM matte", "Saddle stitch|Perfect bind", "cobalt"],
  ["promotional-leaflets", "Promotional Leaflets", "marketing", 399, 100, 4.6, "", "Compact leaflets for offers, local campaigns and direct handouts.", "A5|DL|Square", "100 GSM bond|130 GSM gloss", "Single-sided|Double-sided", "yellow"],
  ["product-catalogues", "Product Catalogues", "marketing", 2499, 25, 4.8, "Recommended", "Premium catalogues that organise product ranges, pricing and sales information.", "A4|A5", "170 GSM matte cover|130 GSM inner", "Perfect bind|Saddle stitch", "ink"],
  ["printed-door-hangers", "Printed Door Hangers", "marketing", 899, 100, 4.6, "", "Targeted door hangers for hospitality, local promotions and service updates.", "3.5 x 8.5 in|4 x 9 in", "300 GSM matte|350 GSM gloss", "Die-cut hole", "coral"],
  ["restaurant-menus", "Restaurant Menus", "marketing", 699, 25, 4.7, "", "Durable printed menus for cafes, restaurants, bars and catering teams.", "A4|A5|DL", "170 GSM matte|300 GSM laminated", "Single-sided|Folded", "yellow"],
  ["promotional-postcards", "Promotional Postcards", "marketing", 549, 100, 4.6, "", "Mail-ready postcards for launches, thank-yous, invitations and offers.", "A6|DL|Square", "300 GSM matte|350 GSM gloss", "Single-sided|Double-sided", "cobalt"],
  ["table-tent-cards", "Table Tent Cards", "marketing", 799, 25, 4.7, "", "Freestanding tent cards for counters, tables, events and in-store offers.", "A5|DL", "300 GSM matte|350 GSM gloss", "Tri-fold tent", "coral"],

  ["employee-welcome-kits", "Employee Welcome Kits", "corporate-gifting", 2499, 10, 4.8, "Popular", "Curated onboarding kits with branded essentials for new joiners and teams.", "Starter|Premium|Executive", "Mixed merchandise", "Custom branding", "cobalt"],
  ["corporate-gift-hampers", "Corporate Gift Hampers", "corporate-gifting", 1999, 10, 4.7, "", "Thoughtful branded hampers for clients, festive gifting and team recognition.", "Standard|Premium", "Curated gift items", "Custom message card", "coral"],
  ["corporate-polo-tshirts", "Corporate Polo T-Shirts", "corporate-gifting", 899, 10, 4.7, "", "Smart branded polo T-shirts for staff uniforms, events and client-facing teams.", "S|M|L|XL|XXL", "Cotton pique|Poly-cotton", "Embroidery|Print", "mint"],
  ["corporate-round-neck-tshirts", "Corporate Round Neck T-Shirts", "corporate-gifting", 599, 10, 4.6, "", "Comfortable branded crew-neck T-shirts for campaigns, teams and giveaways.", "S|M|L|XL|XXL", "Cotton|Dry-fit", "Front|Front + back", "yellow"],
  ["corporate-hoodies", "Corporate Hoodies", "corporate-gifting", 1399, 10, 4.8, "Recommended", "Premium hoodies for employee kits, off-sites and winter teamwear.", "S|M|L|XL|XXL", "Fleece|French terry", "Embroidery|Print", "ink"],
  ["executive-diaries", "Executive Diaries", "corporate-gifting", 799, 25, 4.7, "", "Professional dated or undated diaries with subtle corporate branding.", "A5|B5", "PU leatherette|Hard cover", "Debossing|Foil", "cobalt"],
  ["premium-executive-pens", "Premium Executive Pens", "corporate-gifting", 999, 25, 4.7, "", "Gift-ready metal pens for clients, leadership events and recognitions.", "Standard|Gift box", "Metal", "Laser engraving", "ink"],
  ["stainless-steel-water-bottles", "Stainless Steel Water Bottles", "corporate-gifting", 1099, 10, 4.7, "", "Double-wall branded bottles built for everyday employee and event use.", "500 ml|750 ml", "Stainless steel", "Laser engraving|UV print", "mint"],
  ["branded-laptop-sleeves", "Branded Laptop Sleeves", "corporate-gifting", 1199, 10, 4.6, "", "Protective custom laptop sleeves for welcome kits and corporate gifting.", "13 in|14 in|15.6 in", "Neoprene|Canvas", "Front print", "coral"],
  ["corporate-tote-bags", "Corporate Branded Tote Bags", "corporate-gifting", 499, 25, 4.7, "", "Reusable branded tote bags for conferences, welcome kits and retail gifting.", "Standard|Large", "Canvas|Cotton", "Screen print|DTF print", "yellow"],

  ["expo-welcome-kits", "Expo Welcome Kits", "expo-materials", 3999, 10, 4.8, "Recommended", "A coordinated expo kit with branded essentials for exhibitors, speakers and visitors.", "Starter|Premium", "Mixed merchandise", "Custom branding", "cobalt"],
  ["expo-roll-up-standees", "Expo Roll-Up Standees", "expo-materials", 1999, 1, 4.7, "Popular", "Portable roll-up standees designed for quick exhibition setup and repeat use.", "2.5 x 6 ft|3 x 6 ft", "Premium flex|Fabric", "Stand included", "ink"],
  ["fabric-expo-backdrops", "Fabric Expo Backdrops", "expo-materials", 4999, 1, 4.7, "", "Crease-resistant fabric backdrops for booths, photo walls and stage branding.", "8 x 8 ft|10 x 8 ft", "Stretch fabric", "Frame included", "coral"],
  ["exhibition-booth-panels", "Exhibition Booth Panels", "expo-materials", 6999, 1, 4.6, "", "Modular printed booth panels for polished, consistent exhibition spaces.", "Custom size", "Foam board|Sunboard", "Mounted panels", "cobalt"],
  ["branded-table-covers", "Branded Table Covers", "expo-materials", 1599, 1, 4.7, "", "Custom table covers that turn registration and display tables into branded touchpoints.", "4 ft|6 ft|8 ft", "Polyester fabric", "Full colour print", "mint"],
  ["brochure-display-stands", "Brochure Display Stands", "expo-materials", 2299, 1, 4.6, "", "Portable brochure stands for neat, accessible literature at exhibitions and events.", "A4 pockets|A5 pockets", "Aluminium|Acrylic", "Stand only|Printed header", "yellow"],

  ["die-cut-stickers", "Custom Die-Cut Stickers", "packaging", 499, 50, 4.9, "Popular", "Durable custom-shape stickers for products, parcels and branded packaging.", "2 in|3 in|4 in", "Gloss vinyl|Matte vinyl|Paper", "Kiss cut|Die cut", "mint"],
  ["mailer-boxes", "Custom Printed Mailer Boxes", "packaging", 1499, 25, 4.8, "New", "Sturdy corrugated mailer boxes designed for a memorable unboxing experience.", "8 x 6 x 3 in|10 x 8 x 4 in", "Kraft|White corrugated", "Outside print|Inside + outside", "coral"],
  ["product-label-rolls", "Product Label Rolls", "packaging", 699, 100, 4.7, "", "Professionally printed roll labels for jars, bottles, boxes and retail packs.", "2 in round|3 x 2 in|4 x 2 in", "Matte paper|Gloss paper|Waterproof vinyl", "Permanent adhesive", "yellow"],
  ["packaging-labels", "Packaging Labels", "packaging", 599, 100, 4.7, "", "Custom product labels for jars, pouches, cartons and retail packaging.", "Custom size", "Matte paper|Gloss paper|Vinyl", "Sheet|Roll", "cobalt"],
  ["shipping-labels", "Shipping Labels", "packaging", 649, 100, 4.7, "", "Clear dispatch labels for shipping addresses, handling notes and fulfilment workflows.", "4 x 6 in|A6", "Paper|Thermal compatible", "Sheet|Roll", "yellow"],
  ["sticker-sheets", "Sticker Sheets", "packaging", 449, 50, 4.6, "", "Multi-design sticker sheets for product inserts, packaging and promotions.", "A5|A4", "Matte vinyl|Gloss vinyl", "Kiss cut", "mint"],
  ["custom-stickers", "Custom Stickers", "packaging", 549, 50, 4.8, "Popular", "Branded stickers in custom shapes and finishes for products and everyday packaging.", "Custom size", "Paper|Vinyl|Transparent", "Die cut|Kiss cut", "coral"],
  ["printed-hang-tags", "Printed Hang Tags", "packaging", 699, 100, 4.7, "", "Retail-ready hang tags for apparel, accessories, gifts and premium products.", "2 x 3.5 in|2.5 x 4 in", "300 GSM matte|Kraft", "Rounded corners|Drilled hole", "ink"],
  ["corrugated-shipping-boxes", "Corrugated Shipping Boxes", "packaging", 2299, 25, 4.7, "", "Strong corrugated boxes for secure branded shipping and fulfilment.", "Custom size", "Kraft corrugated|White corrugated", "Outside print", "coral"],
  ["rigid-gift-boxes", "Rigid Gift Boxes", "packaging", 2999, 25, 4.8, "Recommended", "Premium rigid boxes for corporate gifts, luxury retail and special launches.", "Small|Medium|Large", "Rigid board|Wrapped paper", "Foil|Emboss|Print", "ink"],
  ["folding-cartons", "Printed Folding Cartons", "packaging", 1899, 50, 4.7, "", "Custom folding cartons for retail products, cosmetics, food and consumer goods.", "Custom dieline", "300 GSM SBS|Kraft board", "Matte|Gloss|Spot UV", "cobalt"],
  ["custom-product-boxes", "Custom Product Boxes", "packaging", 2499, 25, 4.7, "", "Printed product boxes tailored to your dimensions, finish and brand requirements.", "Custom size", "Kraft|White board", "Outside|Inside + outside", "yellow"],
  ["courier-boxes", "Courier Boxes", "packaging", 1999, 25, 4.6, "", "Sturdy branded courier boxes for D2C, e-commerce and subscription deliveries.", "Small|Medium|Large", "Kraft corrugated", "Outside print", "coral"],
  ["pizza-boxes", "Printed Pizza Boxes", "packaging", 1799, 50, 4.7, "", "Food-safe pizza boxes for restaurants, cloud kitchens and delivery brands.", "7 in|10 in|12 in", "Food-grade corrugated", "Outside print", "yellow"],
  ["sweet-boxes", "Printed Sweet Boxes", "packaging", 1499, 50, 4.7, "", "Festive and retail sweet boxes for gifting, bakeries and celebrations.", "250 g|500 g|1 kg", "Food-grade board", "Matte|Gloss", "coral"],
  ["bottle-packaging-boxes", "Bottle Packaging Boxes", "packaging", 1899, 25, 4.7, "", "Protective custom boxes for beverages, personal care and gift bottles.", "Single bottle|Double bottle", "Rigid board|Corrugated", "Die-cut insert", "ink"],
  ["kraft-paper-bags", "Kraft Paper Bags", "packaging", 999, 100, 4.7, "", "Natural kraft paper bags for retail, takeaway and eco-conscious packaging.", "Small|Medium|Large", "Brown kraft|White kraft", "Single colour|Full colour", "mint"],
  ["printed-paper-carry-bags", "Printed Paper Carry Bags", "packaging", 1299, 100, 4.7, "", "Branded paper carry bags with handles for stores, events and premium purchases.", "Small|Medium|Large", "Art paper|Kraft paper", "Rope handle|Flat handle", "cobalt"],
  ["packaging-tote-bags", "Printed Cotton Tote Bags", "packaging", 599, 25, 4.7, "", "Reusable cotton tote bags for retail packaging, launches and gifting.", "Standard|Large", "Cotton|Canvas", "Screen print|DTF print", "mint"],
  ["packaging-sleeves", "Packaging Sleeves", "packaging", 799, 50, 4.6, "", "Printed sleeves for boxes, trays, jars and premium product wraps.", "Custom size", "250 GSM|300 GSM", "Matte|Gloss", "yellow"],
  ["printed-packaging-tape", "Printed Packaging Tape", "packaging", 899, 36, 4.7, "", "Custom branded tape for secure, recognisable parcel sealing.", "48 mm x 50 m", "BOPP tape", "Single colour|Two colour", "cobalt"],

  ["roll-up-standees", "Premium Roll-Up Standees", "signage", 1899, 1, 4.7, "Popular", "Portable, reusable displays with a premium base for retail and event spaces.", "2.5 x 6 ft|3 x 6 ft", "Premium flex|Fabric", "Stand included", "cobalt"],
  ["vinyl-banners", "Fabric & Vinyl Banners", "signage", 699, 1, 4.7, "", "Indoor and outdoor banners with crisp colour and reinforced finishing options.", "3 x 2 ft|6 x 3 ft|8 x 4 ft", "Fabric|440 GSM vinyl", "Eyelets|Pole pockets", "ink"],
  ["acrylic-signage", "Acrylic Reception Signs", "signage", 1299, 1, 4.8, "Recommended", "Clean, modern acrylic signs for reception desks, offices and storefronts.", "A4|A3|18 x 12 in", "Clear acrylic|Frosted acrylic", "Wall mounts|Desk stand-offs", "cobalt"],
  ["flex-banners", "Flex Banners", "signage", 549, 1, 4.6, "", "Cost-effective flex banners for promotions, storefronts and outdoor events.", "3 x 2 ft|6 x 3 ft|8 x 4 ft", "440 GSM flex", "Eyelets|Pole pockets", "coral"],
  ["foam-display-boards", "Foam Display Boards", "signage", 899, 1, 4.7, "", "Lightweight mounted boards for presentations, retail displays and events.", "A3|A2|A1", "5 mm foam board", "Single-sided|Double-sided", "mint"],
  ["led-sign-boards", "LED Sign Boards", "signage", 4999, 1, 4.7, "New", "Illuminated sign boards for visible storefront, reception and wayfinding branding.", "Custom size", "LED acrylic|LED channel", "Wall mount", "cobalt"],
  ["canvas-sign-prints", "Canvas Sign Prints", "signage", 1199, 1, 4.6, "", "Textured canvas prints for hospitality, retail decor and office walls.", "12 x 18 in|18 x 24 in", "Matte canvas", "Gallery wrap", "coral"],
  ["x-banners", "X-Banners", "signage", 999, 1, 4.6, "", "Portable X-frame banners for events, retail campaigns and quick promotions.", "2 x 5 ft|2.5 x 6 ft", "Flex|Fabric", "Frame included", "yellow"],
  ["reception-signs", "Reception Signs", "signage", 1899, 1, 4.8, "Recommended", "Premium desk and wall signage that gives reception areas a finished look.", "A4|A3|Custom", "Acrylic|Metal", "Wall mount|Desk stand", "ink"],
  ["display-boards", "Display Boards", "signage", 1299, 1, 4.7, "", "Professional display boards for announcements, menus, galleries and retail.", "A3|A2|A1", "Foam board|Sunboard", "Mounted print", "cobalt"],

  ["custom-tshirts", "Custom Round Neck T-Shirts", "apparel", 599, 1, 4.8, "Popular", "Comfortable premium cotton round-neck T-shirts with vibrant, durable custom printing.", "S|M|L|XL|XXL", "White|Black|Navy|Red", "Front|Back|Front + back", "yellow"],
  ["premium-cotton-hoodies", "Premium Cotton Hoodies", "apparel", 1299, 1, 4.8, "Recommended", "Heavyweight branded hoodies finished with high-quality print or embroidery.", "S|M|L|XL|XXL", "Black|Navy|Charcoal", "Chest print|Embroidery|Back print", "ink"],
  ["embroidered-polo-shirts", "Corporate Polo T-Shirts", "apparel", 849, 5, 4.7, "", "Smart, durable polos for uniforms, hospitality teams and corporate events.", "S|M|L|XL|XXL", "Cotton pique|Poly-cotton", "Left chest embroidery|Sleeve embroidery", "mint"],
  ["oversized-tshirts", "Oversized T-Shirts", "apparel", 699, 1, 4.7, "", "Relaxed-fit custom T-shirts for streetwear, merch drops and creative teams.", "S|M|L|XL|XXL", "240 GSM cotton", "Front|Back|Front + back", "coral"],
  ["custom-sweatshirts", "Custom Sweatshirts", "apparel", 1099, 1, 4.7, "", "Comfortable branded sweatshirts for teams, clubs and seasonal merchandise.", "S|M|L|XL|XXL", "Fleece|French terry", "Print|Embroidery", "cobalt"],
  ["custom-sports-jerseys", "Custom Sports Jerseys", "apparel", 799, 10, 4.7, "", "Performance jerseys with names, numbers and team branding for sport and events.", "S|M|L|XL|XXL", "Dry-fit polyester", "Front + back|Name + number", "yellow"],
  ["corporate-uniforms", "Corporate Uniforms", "apparel", 999, 10, 4.7, "", "Coordinated uniforms for retail, hospitality, operations and field teams.", "S|M|L|XL|XXL", "Cotton|Poly-cotton", "Embroidery|Print", "ink"],
  ["custom-caps", "Custom Caps", "apparel", 449, 10, 4.6, "", "Branded caps for teams, promotions, retail and event merchandise.", "Free size", "Cotton twill|Mesh", "Embroidery|Patch", "mint"],
  ["custom-apparel-tote-bags", "Custom Canvas Tote Bags", "apparel", 549, 25, 4.7, "", "Wearable-style canvas totes for merch, stores, events and everyday carry.", "Standard|Large", "Canvas|Cotton", "Screen print|DTF print", "coral"],
  ["branded-aprons", "Branded Aprons", "apparel", 699, 10, 4.7, "", "Hardwearing printed or embroidered aprons for cafes, kitchens and studios.", "Standard|Long", "Cotton canvas|Poly-cotton", "Front print|Embroidery", "yellow"],

  ["photo-mugs", "Personalised Photo Mugs", "gifts", 349, 1, 4.9, "Popular", "A personal ceramic photo mug with a bright, lasting full-wrap print.", "325 ml", "White ceramic|Magic mug", "Full wrap", "mint"],
  ["custom-canvas-prints", "Custom Canvas Prints", "gifts", 999, 1, 4.8, "Recommended", "Gallery-wrapped canvas prints for memorable photos, art and wall displays.", "8 x 8 in|12 x 18 in|18 x 24 in", "Matte canvas", "Gallery wrap", "coral"],
  ["acrylic-photo-blocks", "Acrylic Photo Blocks", "gifts", 799, 1, 4.7, "", "Crystal-clear acrylic blocks that turn favourite photographs into desk displays.", "4 x 4 in|6 x 4 in|8 x 6 in", "Clear acrylic", "Single-sided print", "cobalt"],
  ["magic-photo-mugs", "Magic Photo Mugs", "gifts", 449, 1, 4.7, "", "Heat-reveal mugs that make personal photos and messages feel more special.", "325 ml", "Heat-sensitive ceramic", "Full wrap", "ink"],
  ["personalised-photo-frames", "Personalised Photo Frames", "gifts", 699, 1, 4.7, "", "Custom photo frames for memories, milestones, desks and gifts.", "4 x 6 in|6 x 8 in|8 x 10 in", "MDF|Wood", "Single-sided print", "coral"],
  ["custom-mouse-pads", "Custom Mouse Pads", "gifts", 399, 1, 4.6, "", "Personalised mouse pads for workspaces, gifts and brand giveaways.", "Standard|Extended", "Neoprene", "Full colour print", "cobalt"],
  ["photo-keychains", "Photo Keychains", "gifts", 299, 10, 4.6, "", "Compact personalised keychains for events, gifts and everyday keepsakes.", "Rectangle|Round", "Acrylic|Metal", "Single-sided|Double-sided", "yellow"],
  ["personalised-calendars", "Personalised Calendars", "gifts", 599, 1, 4.7, "", "Photo-led wall and desk calendars for homes, offices and gifting.", "Desk|Wall", "170 GSM matte", "Wire bound|Tent", "mint"],
  ["custom-photo-magnets", "Custom Photo Magnets", "gifts", 349, 10, 4.6, "", "Vibrant photo magnets for celebrations, save-the-dates and gifts.", "2 x 2 in|3 x 3 in", "Magnetic sheet", "Gloss finish", "coral"],
  ["personalised-photo-albums", "Personalised Photo Albums", "gifts", 1499, 1, 4.8, "Recommended", "Premium photo albums for weddings, milestones, portfolios and memories.", "8 x 8 in|12 x 12 in", "Hard cover|Linen cover", "Layflat|Standard", "ink"],
  ["photo-cushions", "Photo Cushions", "gifts", 699, 1, 4.6, "", "Soft custom cushions that turn favourite images into lasting gifts.", "12 x 12 in|16 x 16 in", "Polyester|Velvet", "Single-sided|Double-sided", "yellow"],
  ["personalised-wall-clocks", "Personalised Wall Clocks", "gifts", 899, 1, 4.6, "", "Custom wall clocks for homes, offices, gifts and branded spaces.", "10 in|12 in", "MDF|Acrylic", "Full colour print", "cobalt"],
  ["printoasis-diwali-hamper-kit", "PrintOasis Diwali Hamper Kit", "gifts", 1499, 1, 0, "Limited Edition", "A ready-to-gift festive box with a PrintOasis-branded printed sleeve, 200 g assorted almonds, cashews, raisins and pistachios, 100 g assorted chocolates in sealed retail packaging, two decorative diyas, one greeting card personalised with the recipient’s name and your message, a matching name tag and festive ribbon. Price includes the listed hamper and packaging.", "One hamper", "Gift box", "Printed sleeve, greeting card and name tag", "ink", { prelaunch: true }],

  ["letterheads", "Premium Company Letterheads", "stationery", 599, 100, 4.7, "", "Professional letterheads on smooth, writing-friendly premium stock.", "A4", "100 GSM bond|120 GSM premium", "Single-sided", "cobalt"],
  ["business-envelopes", "Branded Business Envelopes", "stationery", 699, 100, 4.7, "", "Professional envelopes for invoices, correspondence and corporate mailers.", "DL|C5|C4", "100 GSM bond|120 GSM premium", "Front print|Front + flap", "yellow"],
  ["presentation-folders", "Presentation Folders", "stationery", 1199, 25, 4.8, "Recommended", "Premium document folders with business card slots for meetings and proposals.", "A4", "300 GSM matte|350 GSM laminated", "Single-sided|Double-sided", "coral"],
  ["invoice-books", "Invoice Books", "stationery", 899, 10, 4.7, "", "Numbered invoice books for retail, service businesses and field teams.", "A5|A4", "NCR paper", "Duplicate|Triplicate", "cobalt"],
  ["branded-notebooks", "Branded Notebooks", "stationery", 699, 25, 4.7, "", "Custom notebooks for meetings, onboarding, events and everyday work.", "A5|B5", "Hard cover|Soft cover", "Wire bound|Perfect bind", "mint"],
  ["office-diaries", "Office Diaries", "stationery", 799, 25, 4.7, "", "Professional branded diaries for planning, gifting and executive desks.", "A5|B5", "Hard cover|PU leatherette", "Debossing|Foil", "ink"],
  ["printed-certificates", "Printed Certificates", "stationery", 499, 25, 4.6, "", "Formal certificates for training, awards, schools and recognitions.", "A4|A5", "220 GSM matte|300 GSM textured", "Single-sided", "yellow"],
  ["files-and-folders", "Files & Folders", "stationery", 1299, 25, 4.7, "", "Custom document files and folders for proposals, onboarding and office use.", "A4", "300 GSM board|PVC", "Pocket|Elastic closure", "coral"],
  ["printed-id-cards", "Printed ID Cards", "stationery", 799, 25, 4.7, "", "Professional staff and visitor ID cards with optional variable details.", "CR80", "PVC", "Single-sided|Double-sided", "cobalt"],
  ["branded-lanyards", "Branded Lanyards", "stationery", 699, 25, 4.6, "", "Custom lanyards for employee IDs, conferences and visitor management.", "15 mm|20 mm", "Polyester", "Single-sided|Double-sided", "mint"],

  ["express-flyers", "Same-Day Flyers", "same-day", 499, 50, 4.6, "Popular", "Urgent flyers produced quickly without compromising colour or finish.", "A5|A4", "130 GSM gloss|170 GSM matte", "Single-sided|Double-sided", "coral"],
  ["same-day-business-cards", "Same-Day Business Cards", "same-day", 649, 100, 4.7, "", "Essential business cards produced on an accelerated schedule for urgent needs.", "3.5 x 2 in", "300 GSM matte|350 GSM gloss", "Single-sided|Double-sided", "cobalt"],
  ["same-day-posters", "Same-Day Posters", "same-day", 349, 5, 4.6, "", "Fast-turnaround posters for announcements, menus and event promotions.", "A3|A2", "170 GSM matte|200 GSM gloss", "Full colour", "yellow"],
  ["same-day-stickers", "Same-Day Stickers", "same-day", 549, 50, 4.6, "", "Quick-turn stickers for urgent labels, event packs and short campaigns.", "2 in|3 in|4 in", "Paper|Gloss vinyl", "Kiss cut", "mint"],
  ["same-day-x-banners", "Same-Day X-Banners", "same-day", 1099, 1, 4.6, "", "Fast X-banner production for launches, counters and urgent event needs.", "2 x 5 ft|2.5 x 6 ft", "Flex", "Frame included", "coral"],

  ["bulk-corporate-stationery", "Bulk Corporate Stationery", "bulk", 5499, 500, 4.8, "Recommended", "Coordinated high-volume business cards, letterheads and envelopes for teams.", "Custom bundle", "Premium paper stocks", "Brand-matched print", "cobalt"],
  ["bulk-marketing-kits", "Bulk Marketing Kits", "bulk", 8999, 250, 4.8, "", "Campaign-ready bulk flyers, brochures and posters with consistent brand colour.", "Custom bundle", "Marketing print stocks", "Mixed-format print", "coral"],
  ["bulk-packaging-labels", "Bulk Packaging Labels", "bulk", 3999, 1000, 4.7, "New", "High-volume labels for retail, FMCG and fulfilment operations.", "Custom size", "Paper|Vinyl|Waterproof film", "Roll labels", "mint"],
  ["bulk-business-cards", "Bulk Business Cards", "bulk", 7999, 1000, 4.8, "Popular", "Large-run business cards with consistent colour, finish and delivery planning.", "3.5 x 2 in", "300 GSM matte|350 GSM gloss", "Single-sided|Double-sided", "cobalt"],
  ["bulk-flyers", "Bulk Flyers", "bulk", 4999, 1000, 4.7, "", "High-volume flyers for launches, inserts, local campaigns and national rollouts.", "A5|A4|DL", "100 GSM|130 GSM gloss", "Single-sided|Double-sided", "coral"],
  ["bulk-brochures", "Bulk Brochures", "bulk", 12999, 500, 4.8, "Recommended", "Volume brochure runs for distributors, sales teams and campaign fulfilment.", "A4|A5", "130 GSM|170 GSM", "Tri-fold|Bi-fold", "ink"],
  ["bulk-packaging-boxes", "Bulk Packaging Boxes", "bulk", 14999, 250, 4.7, "", "Commercial packaging box runs for retail, D2C and fulfilment operations.", "Custom size", "Kraft|White corrugated", "Outside print", "yellow"],
  ["bulk-paper-bags", "Bulk Paper Bags", "bulk", 7999, 500, 4.7, "", "Branded paper bags for stores, events, food service and retail programmes.", "Small|Medium|Large", "Kraft|Art paper", "Handle options", "mint"],
  ["bulk-tote-bags", "Bulk Cotton Tote Bags", "bulk", 9999, 250, 4.7, "", "Volume cotton tote bags for events, retail, campaigns and giveaways.", "Standard|Large", "Cotton|Canvas", "Screen print|DTF print", "coral"],
  ["bulk-tshirts", "Bulk T-Shirts", "bulk", 14999, 100, 4.7, "", "High-volume custom T-shirts for teams, events, promotions and retail launches.", "S|M|L|XL|XXL", "Cotton|Dry-fit", "Front|Front + back", "cobalt"],
  ["bulk-notebooks", "Bulk Notebooks", "bulk", 11999, 100, 4.7, "", "Custom notebooks for conferences, onboarding, training and campaigns.", "A5|B5", "Hard cover|Soft cover", "Wire bound|Perfect bind", "yellow"],
  ["bulk-corporate-welcome-kits", "Bulk Corporate Welcome Kits", "bulk", 24999, 50, 4.8, "Recommended", "Coordinated welcome kits for large onboarding programmes and multi-location teams.", "Starter|Premium", "Mixed merchandise", "Custom branding", "ink"]
];

// Prelaunch products use an explicit zero-stock seed so they can be reviewed
// through normal catalogue, detail and search routes without being purchasable.
const productCollections = {
  "limited-editions": ["printoasis-diwali-hamper-kit"]
};

// A commercial catalog should lead with the products customers ask for most often.
// Admin-created products remain available, but follow these curated launch products.
const productPriorities = {
  "business-cards": ["standard-business-cards", "premium-business-cards", "matte-business-cards", "gloss-business-cards", "spot-uv-business-cards", "premium-foil-cards", "textured-business-cards", "transparent-business-cards", "eco-friendly-business-cards", "classic-business-cards"],
  marketing: ["professional-flyers", "folded-brochures", "marketing-booklets", "event-posters", "product-catalogues", "promotional-postcards", "printed-door-hangers", "restaurant-menus", "promotional-leaflets", "table-tent-cards"],
  "corporate-gifting": ["employee-welcome-kits", "corporate-polo-tshirts", "corporate-round-neck-tshirts", "corporate-tote-bags", "executive-diaries", "premium-executive-pens", "stainless-steel-water-bottles", "branded-laptop-sleeves", "corporate-hoodies", "corporate-gift-hampers"],
  "expo-materials": ["expo-welcome-kits", "expo-roll-up-standees", "fabric-expo-backdrops", "exhibition-booth-panels", "branded-table-covers", "brochure-display-stands"],
  packaging: ["corrugated-shipping-boxes", "mailer-boxes", "custom-product-boxes", "rigid-gift-boxes", "courier-boxes", "printed-paper-carry-bags", "packaging-tote-bags", "packaging-labels", "custom-stickers", "printed-hang-tags", "printed-packaging-tape", "packaging-sleeves", "folding-cartons", "product-label-rolls", "shipping-labels", "sticker-sheets", "die-cut-stickers", "pizza-boxes", "sweet-boxes", "bottle-packaging-boxes", "kraft-paper-bags"],
  signage: ["roll-up-standees", "flex-banners", "vinyl-banners", "reception-signs", "foam-display-boards", "acrylic-signage", "led-sign-boards", "canvas-sign-prints", "display-boards", "x-banners"],
  apparel: ["embroidered-polo-shirts", "custom-tshirts", "custom-sports-jerseys", "corporate-uniforms", "premium-cotton-hoodies", "custom-sweatshirts", "oversized-tshirts", "custom-caps", "custom-apparel-tote-bags", "branded-aprons"],
  gifts: ["photo-mugs", "personalised-photo-frames", "magic-photo-mugs", "personalised-photo-albums", "personalised-calendars", "personalised-wall-clocks", "custom-mouse-pads", "custom-photo-magnets", "photo-keychains", "photo-cushions", "custom-canvas-prints", "acrylic-photo-blocks", "printoasis-diwali-hamper-kit"],
  stationery: ["letterheads", "business-envelopes", "presentation-folders", "branded-notebooks", "office-diaries", "invoice-books", "printed-certificates", "printed-id-cards", "files-and-folders", "branded-lanyards"],
  "same-day": ["same-day-business-cards", "express-flyers", "same-day-posters", "same-day-stickers", "same-day-x-banners"],
  bulk: ["bulk-business-cards", "bulk-flyers", "bulk-brochures", "bulk-packaging-boxes", "bulk-packaging-labels", "bulk-paper-bags", "bulk-tote-bags", "bulk-tshirts", "bulk-notebooks", "bulk-corporate-welcome-kits", "bulk-corporate-stationery", "bulk-marketing-kits"]
};

module.exports = { categories, products, productPriorities, productCollections };
