module.exports = async function accountRoutes(ctx) {
  const { req, res, url, data, session, cart, app } = ctx;
  if (req.method === "GET" && url.pathname.startsWith("/artwork/")) { await app.serveArtwork(req, res, url, session); return true; }
  if (req.method === "GET" && (url.pathname === "/account" || url.pathname === "/account/orders")) { if (!app.requireAuth(session, res, url.pathname)) return true; app.send(res, 200, url.pathname.endsWith("orders") ? await app.ordersPage(session, cart, url) : await app.accountPage(url, session, cart)); return true; }
  if (req.method === "GET" && url.pathname.startsWith("/account/orders/")) { if (!app.requireAuth(session, res, url.pathname)) return true; const orderId = Number(url.pathname.slice("/account/orders/".length)); const order = Number.isInteger(orderId) && orderId > 0 ? await app.orderWithUser(orderId) : null; if (!order || order.user_id !== session.user.id) { app.redirect(res, "/account/orders?notice=" + encodeURIComponent("Order not found.")); return true; } app.send(res, 200, await app.orderDetailsPage(order, session, cart)); return true; }
  if (req.method === "GET" && url.pathname === "/wishlist") { if (!app.requireAuth(session, res, "/wishlist")) return true; app.send(res, 200, await app.wishlistPage(session, cart)); return true; }
  if (req.method === "GET" && url.pathname === "/account/addresses") { if (!app.requireAuth(session, res, url.pathname)) return true; app.send(res, 200, await app.addressesPage(url, session, cart)); return true; }
  if (req.method === "GET" && url.pathname === "/account/password") { if (!app.requireAuth(session, res, url.pathname)) return true; app.send(res, 200, await app.passwordPage(url, session, cart)); return true; }
  if (req.method === "GET" && url.pathname === "/track") return app.send(res, 200, await app.trackPage(url, session, cart)), true;
  if (req.method === "POST" && url.pathname === "/track") { if (!app.validCsrf(data, session)) return app.send(res, 403, "Invalid form token", "text/plain"), true; const order = await app.db.get("SELECT * FROM orders WHERE order_number = ? AND phone = ?", (data.order_number || "").trim().toUpperCase(), (data.phone || "").trim()); app.send(res, 200, order ? await app.trackPage(url, session, cart, order) : await app.trackPage(new URL("/track?notice=Order+not+found.", app.requestOrigin(req)), session, cart)); return true; }
  const infoRoutes = { "/help": "help", "/contact": "contact", "/business": "business", "/faq": "faq", "/shipping-policy": "shipping", "/returns": "returns", "/privacy": "privacy", "/terms": "terms", "/printing-guidelines": "guidelines", "/resources": "resources" };
  if (req.method === "GET" && infoRoutes[url.pathname]) { app.send(res, 200, await app.infoPage(infoRoutes[url.pathname], session, cart, url)); return true; }
  if (req.method === "POST" && url.pathname === "/contact") { if (!app.validCsrf(data, session)) return app.send(res, 403, "Invalid form token", "text/plain"), true; const name = String(data.name || "").trim(), email = String(data.email || "").trim(), phone = String(data.phone || "").trim(), message = String(data.message || "").trim(); if (name.length < 2 || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email) || phone.length < 7 || message.length < 12) return app.redirect(res, "/contact?notice=" + encodeURIComponent("Please complete every contact field with valid details.")), true; await app.sendContactEnquiry({ name, email, phone, topic: data.topic, message }); app.redirect(res, "/contact?notice=" + encodeURIComponent("Thanks. Your enquiry is with the PrintOasis team.")); return true; }
  if (req.method !== "POST") return false;
  const posts = ["/account/orders/reorder", "/account/reviews/save", "/account/reviews/delete", "/account/addresses/save", "/account/addresses/default", "/account/addresses/delete", "/account/password"];
  if (!posts.includes(url.pathname)) return false;
  if (!app.requireAuth(session, res, "/account")) return true;
  if (!app.validCsrf(data, session)) return app.send(res, 403, "Invalid form token", "text/plain"), true;
  if (url.pathname === "/account/orders/reorder") {
    const order = await app.db.get("SELECT id FROM orders WHERE id = ? AND user_id = ?", Number(data.order_id), session.user.id); if (!order) return app.redirect(res, "/account/orders?notice=Order+not+found."), true;
    const items = await app.db.all("SELECT oi.*, p.id AS current_product_id, p.slug, p.sizes, p.materials, p.print_options, p.price, p.min_qty, p.stock, p.reserved, p.status, p.active FROM order_items oi LEFT JOIN products p ON p.id = oi.product_id WHERE oi.order_id = ?", order.id);
    const skipped = []; let added = 0;
    await app.db.transaction(async tx => { for (const item of items) { if (!item.current_product_id || !item.slug || !item.active || item.status === "hidden") { skipped.push(item.product_name); continue; } const locked = await tx.get(`SELECT * FROM products WHERE id=? AND ${app.visibleProductCondition()} FOR UPDATE`, item.current_product_id); if (!locked) { skipped.push(item.product_name); continue; } const config = String(item.configuration || "").split(" · "); try { await app.addCartItem(session.id, locked, item.quantity, { size: config[0] || String(item.sizes || "").split("|")[0], material: config[1] || String(item.materials || "").split("|")[0], printOption: config[2] || String(item.print_options || "").split("|")[0] }, tx); added += 1; } catch { skipped.push(item.product_name); } } });
    const message = [(added ? `${added} item${added === 1 ? "" : "s"} added to your cart.` : "No items could be added."), skipped.length ? `Skipped: ${[...new Set(skipped)].join(", ")}.` : ""].filter(Boolean).join(" "); app.redirect(res, "/cart?notice=" + encodeURIComponent(message)); return true;
  }
  if (url.pathname === "/account/reviews/save") { const order = await app.db.get("SELECT id FROM orders WHERE id = ? AND user_id = ? AND status = 'Delivered'", Number(data.order_id), session.user.id), productId = Number(data.product_id), ordered = order && await app.db.get("SELECT 1 FROM order_items WHERE order_id = ? AND product_id = ?", order.id, productId), rating = Math.max(1, Math.min(5, Number(data.rating) || 5)), comment = String(data.comment || "").trim().slice(0, 600); if (!ordered || !await app.hasDeliveredPurchase(session.user.id, productId)) return app.redirect(res, "/account/orders?notice=Only+verified+delivered+purchases+can+be+reviewed."), true; if (comment.length < 8) return app.redirect(res, `/account/orders/${order.id}?notice=Review+must+contain+at+least+8+characters.`), true; const existing = await app.db.get("SELECT id FROM reviews WHERE user_id = ? AND product_id = ?", session.user.id, productId); if (existing) await app.db.run("UPDATE reviews SET rating=?, comment=?, verified_purchase=1, updated_at=CURRENT_TIMESTAMP WHERE id=? AND user_id=?", rating, comment, existing.id, session.user.id); else await app.db.run("INSERT INTO reviews (product_id,user_id,name,rating,comment,verified_purchase) VALUES (?,?,?,?,?,1)", productId, session.user.id, session.user.name, rating, comment); app.redirect(res, `/account/orders/${order.id}?notice=${encodeURIComponent(existing ? "Review updated." : "Review submitted.")}`); return true; }
  if (url.pathname === "/account/reviews/delete") { const order = await app.db.get("SELECT id FROM orders WHERE id=? AND user_id=?", Number(data.order_id), session.user.id), review = await app.db.get("SELECT id, product_id FROM reviews WHERE id=? AND user_id=?", Number(data.review_id), session.user.id), ordered = order && review && await app.db.get("SELECT 1 FROM order_items WHERE order_id=? AND product_id=?", order.id, review.product_id); if (!ordered) return app.redirect(res, "/account/orders?notice=Review+not+found."), true; await app.db.run("DELETE FROM reviews WHERE id=? AND user_id=?", review.id, session.user.id); app.redirect(res, `/account/orders/${order.id}?notice=Review+deleted.`); return true; }
  if (url.pathname === "/account/addresses/save") { const id = Number(data.id || 0), values = { label: String(data.label || "").trim().slice(0, 40), recipientName: String(data.recipient_name || "").trim().slice(0, 100), phone: String(data.phone || "").trim().slice(0, 30), address: String(data.address || "").trim().slice(0, 500), city: String(data.city || "").trim().slice(0, 100), postalCode: String(data.postal_code || "").trim() }; if (!values.label || !values.recipientName || !values.phone || !values.address || !values.city || !/^[0-9]{6}$/.test(values.postalCode)) return app.redirect(res, "/account/addresses?notice=Please+enter+a+complete+delivery+address."), true; const current = id ? await app.db.get("SELECT * FROM addresses WHERE id=? AND user_id=?", id, session.user.id) : null; if (id && !current) return app.redirect(res, "/account/addresses?notice=Address+not+found."), true; const count = Number((await app.db.get("SELECT COUNT(*) count FROM addresses WHERE user_id=?", session.user.id)).count), makeDefault = Boolean(data.is_default) || Boolean(current?.is_default) || !count; await app.db.transaction(async tx => { if (makeDefault) await tx.run("UPDATE addresses SET is_default=0 WHERE user_id=?", session.user.id); if (current) await tx.run("UPDATE addresses SET label=?,recipient_name=?,phone=?,address=?,city=?,postal_code=?,is_default=? WHERE id=? AND user_id=?", values.label, values.recipientName, values.phone, values.address, values.city, values.postalCode, makeDefault ? 1 : 0, current.id, session.user.id); else await tx.run("INSERT INTO addresses (user_id,label,recipient_name,phone,address,city,postal_code,is_default) VALUES (?,?,?,?,?,?,?,?)", session.user.id, values.label, values.recipientName, values.phone, values.address, values.city, values.postalCode, makeDefault ? 1 : 0); }); app.redirect(res, "/account/addresses?notice=Address+saved."); return true; }
  if (url.pathname === "/account/addresses/default") { const address = await app.db.get("SELECT id FROM addresses WHERE id=? AND user_id=?", Number(data.id), session.user.id); if (!address) return app.redirect(res, "/account/addresses?notice=Address+not+found."), true; await app.db.transaction(async tx => { await tx.run("UPDATE addresses SET is_default=0 WHERE user_id=?", session.user.id); await tx.run("UPDATE addresses SET is_default=1 WHERE id=? AND user_id=?", address.id, session.user.id); }); app.redirect(res, "/account/addresses?notice=Default+address+updated."); return true; }
  if (url.pathname === "/account/addresses/delete") { const address = await app.db.get("SELECT id,is_default FROM addresses WHERE id=? AND user_id=?", Number(data.id), session.user.id); if (!address) return app.redirect(res, "/account/addresses?notice=Address+not+found."), true; await app.db.transaction(async tx => { await tx.run("DELETE FROM addresses WHERE id=? AND user_id=?", address.id, session.user.id); if (address.is_default) { const replacement = await tx.get("SELECT id FROM addresses WHERE user_id=? ORDER BY id DESC LIMIT 1", session.user.id); if (replacement) await tx.run("UPDATE addresses SET is_default=1 WHERE id=?", replacement.id); } }); app.redirect(res, "/account/addresses?notice=Address+deleted."); return true; }
  if (url.pathname === "/account/password") { const user = await app.db.get("SELECT * FROM users WHERE id=?", session.user.id), currentPassword = String(data.current_password || ""), newPassword = String(data.new_password || ""); if (!user || !app.verifyPassword(currentPassword, user.password_hash)) return app.redirect(res, "/account/password?notice=Current+password+is+incorrect."), true; if (newPassword.length < 8 || newPassword !== String(data.confirm_password || "")) return app.redirect(res, "/account/password?notice=New+passwords+must+match+and+contain+at+least+8+characters."), true; await app.db.run("UPDATE users SET password_hash=? WHERE id=?", app.hashPassword(newPassword), session.user.id); await app.revokeUserSessions(session.user.id, session.id); app.redirect(res, "/account/password?notice=Password+updated."); return true; }
  return false;
};
